openapi: 3.0.0
info:
  version: 1.0.0
  title: DOCUMENTATION
  description: ''
  termsOfService: YOUR_TERMS_OF_SERVICE_URL
  contact:
    name: TEAM
    email: contact-email@something.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-generation-date: 02/01/2022 12:55:05 PM
x-strapi-config:
  path: "/documentation"
  showGeneratedFiles: true
  generateDefaultResponse: true
servers:
  - url: http://localhost:1337
    description: Development server
  - url: YOUR_STAGING_SERVER
    description: Staging server
  - url: YOUR_PRODUCTION_SERVER
    description: Production server
externalDocs:
  description: Find out more
  url: https://strapi.io/documentation/developer-docs/latest/getting-started/introduction.html
security:
  - bearerAuth: []
paths:
  "/projects":
    get:
      deprecated: false
      description: ''
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      parameters:
        - name: _limit
          in: query
          required: false
          description: Maximum number of results possible
          schema:
            type: integer
          deprecated: false
        - name: _sort
          in: query
          required: false
          description: Sort according to a specific field.
          schema:
            type: string
          deprecated: false
        - name: _start
          in: query
          required: false
          description: Skip a specific number of entries (especially useful for pagination)
          schema:
            type: integer
          deprecated: false
        - name: "="
          in: query
          required: false
          description: Get entries that matches exactly your input
          schema:
            type: string
          deprecated: false
        - name: _ne
          in: query
          required: false
          description: Get records that are not equals to something
          schema:
            type: string
          deprecated: false
        - name: _lt
          in: query
          required: false
          description: Get record that are lower than a value
          schema:
            type: string
          deprecated: false
        - name: _lte
          in: query
          required: false
          description: Get records that are lower than or equal to a value
          schema:
            type: string
          deprecated: false
        - name: _gt
          in: query
          required: false
          description: Get records that are greater than a value
          schema:
            type: string
          deprecated: false
        - name: _gte
          in: query
          required: false
          description: Get records that are greater than  or equal a value
          schema:
            type: string
          deprecated: false
        - name: _contains
          in: query
          required: false
          description: Get records that contains a value
          schema:
            type: string
          deprecated: false
        - name: _containss
          in: query
          required: false
          description: Get records that contains (case sensitive) a value
          schema:
            type: string
          deprecated: false
        - name: _in
          in: query
          required: false
          description: Get records that matches any value in the array of values
          schema:
            type: array
            items:
              type: string
          deprecated: false
        - name: _nin
          in: query
          required: false
          description: Get records that doesn't match any value in the array of values
          schema:
            type: array
            items:
              type: string
          deprecated: false
    post:
      deprecated: false
      description: Create a new record
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProject"
  "/projects/count":
    get:
      deprecated: false
      description: ''
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                properties:
                  count:
                    type: integer
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      parameters: []
  "/projects/{id}":
    get:
      deprecated: false
      description: ''
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      parameters:
        - name: id
          in: path
          description: ''
          deprecated: false
          required: true
          schema:
            type: string
    put:
      deprecated: false
      description: Update a record
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewProject"
      parameters:
        - name: id
          in: path
          description: ''
          deprecated: false
          required: true
          schema:
            type: string
    delete:
      deprecated: false
      description: Delete a record
      responses:
        '200':
          description: deletes a single record based on the ID supplied
          content:
            application/json:
              schema:
                type: integer
                format: int64
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      summary: ''
      tags:
        - Project
      parameters:
        - name: id
          in: path
          description: ''
          deprecated: false
          required: true
          schema:
            type: string
components:
  schemas:
    Project:
      required:
        - id
        - title
      properties:
        id:
          type: string
        title:
          type: string
          maxLength: 255
          minLength: 2
        published_at:
          type: string
          format: date-time
    NewProject:
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 255
          minLength: 2
        published_at:
          type: string
          format: date-time
        created_by:
          type: string
        updated_by:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Project
